### ISSUE TITLE
Document version of python required

### ISSUE THREAD

**Issue by edalquist** [lucidBrot/migrate-from-google-play-music#2]
It took me a fair bit of trial and error to figure out python 3.7+ was needed to run this. On ubuntu the default python is still 2.7 and the default python3 is 3.6.

I needed to do:

```
sudo apt install python3.7 pip3
pip3 install mutagen
python3.7 convert.py
```

**Comment by lucidBrot** [comment]
Thank you for reporting this, I have made the version clear in the README now (The `environment.yml` already had the correct version.)

I didn't realize that the `@dataclass` annotation was this new - it was only introduced in `3.7`.
