### ISSUE TITLE
crash in Mutagen on unexpected amazon.temp file

### ISSUE THREAD

**Issue by skierpage** [lucidBrot/migrate-from-google-play-music#3]
I ran the command in the README
```
python convert.py -c "import * from convert; lmfi=debug_create_lmfi_sans_tags(); compute_redundant_files(lmfi);"
```
and it reliably crashed in the "Indexing local music file tags..." step with `IOError`. Traceback ends with
```
  File "/usr/lib/python3.9/site-packages/mutagen/_util.py", line 657, in read_full
```
I loaded it in a debugger with `python -m pdb convert.py -c "import * from convert; lmfi=debug_create_lmfi_sans_tags(); compute_redundant_files(lmfi);"`, entered `continue`, and at the crash entered `list` to see the code, and saw a `fileobj` variable. Dumping this gave
```
(Pdb) fileobj
<_io.BufferedReader name='/home/spage/Music/Media/Vienna Teng/Waking Hour/amazon.temp'>
```
`amazon.temp` seems to be some leftover from downloading a purchased MP3 digital album from Amazon. I only have one and there are a handful of Google results for `amazon.temp`. `file`(1) reports "Audio file with ID3 version 2.3.0" but it's only 79kB and vlc and ffmpeg can't play it.

The obvious fix is to move the bogus file out of your music path, or delete it.

Feel free to close this bug, but it stumped me, and maybe the steps to track down are useful. It's unfortunate that programs can't print the file they're working on when they encounter an error.

I also got a crash on a symbolic link with a missing target, but that was easy to figure out because python helpfully printed
```
mutagen.MutagenError: [Errno 2] No such file or directory: '/home/spage/Music/temp_to_import/THE BEATLES'
```

**Comment by lucidBrot** [comment]
Thanks for reporting! I'll have a look once I've got some time. Maybe I can skip files mutagen crashes on.

**Comment by skierpage** [comment]
Thanks for your prompt response! this is very low priority. I can reproduce with bare `mutagen.File("amazon.temp"), so I also filed [an issue with Mutagen](https://github.com/quodlibet/mutagen/issues/508).

**Comment by lucidBrot** [comment]
I'm closing this here, since Mutagen accepted that as an open bug. If anybody in the future has the same problem, feel free to reach out again if I need to implement a fix. I think the workaround is clear for now - removing the file so that mutagen does not crash on it.
