### ISSUE TITLE
-c import command line doesn't work

### ISSUE THREAD

**Issue by skierpage** [lucidBrot/migrate-from-google-play-music#8]
`convert.py` and `README.md` suggest the Python command line
```bash
python convert.py -c "import * from convert; lmfi=debug_create_lmfi_sans_tags(); compute_redundant_files(lmfi);"
```
This doesn't work for me with Python 3.9.6:
```
  File "<string>", line 1
    import * from convert; lmfi=debug_create_lmfi_sans_tags(); compute_redundant_files(lmfi);
           ^
SyntaxError: invalid syntax
```
I think the correct command syntax is `from convert import *`

**Comment by lucidBrot** [comment]
Thanks! Apparently I tested this less than I thought. I updated the files.

Nice to hear that the script is still in use despite GPM no longer being a thing :)
